### ISSUE TITLE
Unable to Disarm

### ISSUE THREAD

**Issue by digitalconverg** [markberndt/concord2mqtt#2]
Arming from HASS works great.  Cannot disarm.  Set DirectDisarm to true.  Tried all userids including 246 for system master.
 would appreciate configuration.yaml example for alarm_control_panel to pass remote code for disarm
 
 ```
alarm_control_panel:
   - platform: mqtt
     state_topic: "homeassistant/alarm_control_panel/panel_partition_1/state"
     command_topic: "homeassistant/alarm_control_panel/panel_partition_1/command"
    name: "Panel Partition 1"
     value_template: "{{ value_json.state }}"
     code: REMOTE_CODE
     command_template: "{ action: '{{ action }}', code: '{{ code }}'}"
     code_arm_required: false
     code_disarm_required: true
```
