### ISSUE TITLE
Need help with docker-compose and missing libnserial.so.1

### ISSUE THREAD

**Issue by KewlGuyRox** [markberndt/concord2mqtt#3]
I have HA installed on a VM and the SuperBus module connected via USB to Serial. HA can see the USB Serial.

I am trying to get this work with docker-compose but I am getting errors since it cannot locate your github directly and searches for Dockerfile. Only way I can get it installed is to download the entire repo and run it locally. Is this the right way?

Also I am getting this error once the install completes 

WARNING: Image for service concord2mqtt was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating concord2mqtt_concord2mqtt_1 ... done
Attaching to concord2mqtt_concord2mqtt_1
concord2mqtt_1  | info: Automation.Concord2Mqtt.Host[0]
concord2mqtt_1  |       Concord2Mqtt started at 01/20/2022 22:43:44 -05:00
concord2mqtt_1  | info: Microsoft.Hosting.Lifetime[0]
concord2mqtt_1  |       Application started. Press Ctrl+C to shut down.
concord2mqtt_1  | info: Microsoft.Hosting.Lifetime[0]
concord2mqtt_1  |       Hosting environment: Production
concord2mqtt_1  | info: Microsoft.Hosting.Lifetime[0]
concord2mqtt_1  |       Content root path: /app
concord2mqtt_1  | fail: Automation.Concord2Mqtt.Host[0]
concord2mqtt_1  |       Host failed to start home automation server
concord2mqtt_1  |       System.DllNotFoundException: Unable to load shared library 'libnserial.so.1' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibnserial.so.1: cannot open shared object file: No such file or directory
concord2mqtt_1  |          at RJCP.IO.Ports.Native.Unix.UnsafeNativeMethods.serial_init()
concord2mqtt_1  |          at RJCP.IO.Ports.Native.Unix.SerialUnix.serial_init()
concord2mqtt_1  |          at RJCP.IO.Ports.Native.UnixNativeSerial..ctor()
concord2mqtt_1  |          at RJCP.IO.Ports.SerialPortStream.CreateNativeSerial()
concord2mqtt_1  |          at RJCP.IO.Ports.SerialPortStream..ctor()
concord2mqtt_1  |          at RJCP.IO.Ports.SerialPortStream..ctor(String port)
concord2mqtt_1  |          at RJCP.IO.Ports.SerialPortStream..ctor(String port, Int32 baud, Int32 data, Parity parity, StopBits stopbits)
concord2mqtt_1  |          at Automation.Concord.SerialCommunicationDevice.ConfigureSerialPort(String portName) in /src/Concord/Communication Devices/SerialCommunicationDevice.cs:line 73
concord2mqtt_1  |          at Automation.Concord.SerialCommunicationDevice..ctor(String portName) in /src/Concord/Communication Devices/SerialCommunicationDevice.cs:line 26
concord2mqtt_1  |          at Automation.Concord2Mqtt.Concord2Mqtt..ctor(ILogger logger, Concord2MqttConfiguration settings, ConcordConfiguration concordSettings) in /src/Concord2Mqtt/Concord2Mqtt.cs:line 37
concord2mqtt_1  |          at Automation.Concord2Mqtt.Host.<StartAsync>b__6_0() in /src/Concord2Mqtt/Host.cs:line 50
concord2mqtt_1  | info: Automation.Concord2Mqtt.Host[0]
concord2mqtt_1  |       Failed to start home automation server. Restarting in 5 seconds
concord2mqtt_1  | info: Automation.Concord2Mqtt.Host[0]
concord2mqtt_1  |       Concord2Mqtt started at 01/20/2022 22:43:49 -05:00

**Comment by digitalconverg** [comment]
you need to clone the repo and modify the docker-compose.yml to use the directory where you placed the files.  The Dockerfile is part of the repo. 

I modified the docker-compose.yml with the following:
```
  concord2mqtt:
    image: concord2mqtt:latest
    container_name: concord2mqtt
    environment:
      - TZ=America/New_York
      - Logging__LogLevel__Default=Information
    build:
      context: ./concord/concord2mqtt/
      args:
        - BUILD=Release
      dockerfile: Dockerfile
    volumes:
      - ./concord/concord2mqtt/appsettings.json:/app/appsettings.json
    ports:
      - 9100:9100
    restart: unless-stopped

```
as you can see, I placed the repo in a directory called concord/concord2mqtt off the directory which has the docker-compose.yml file.  The context: allows the build to succeed.  Also note the appsettings.json file is in the same directory as the repo so you will need to customize the example from the repo or choose a different directory to place it in.
